//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ..//android/com/vals/a2ios/mobilighter/intf/MobilCall.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "com/vals/a2ios/mobilighter/intf/MobilCall.h"
#include "com/vals/a2ios/mobilighter/intf/MobilCallBack.h"
#include "java/lang/Exception.h"
#include "java/util/Map.h"

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(MobilCall)
