//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ..//android/com/vals/a2ios/mobilighter/intf/MobilCall.java
//

#ifndef _ComValsA2iosMobilighterIntfMobilCall_H_
#define _ComValsA2iosMobilighterIntfMobilCall_H_

#include "J2ObjC_header.h"

@protocol JavaUtilMap;
@protocol MobilCallBack;

@protocol MobilCall < NSObject, JavaObject >

- (void)setBaseUrlWithNSString:(NSString *)baseUrl;

- (void)setRelativeUrlWithNSString:(NSString *)relativeUrl;

- (void)setCallBackWithMobilCallBack:(id<MobilCallBack>)callBack;

- (void)addHeaderWithNSString:(NSString *)name
                 withNSString:(NSString *)value;

- (id<MobilCallBack>)getCallBack;

- (void)setCookieHeaderWithNSString:(NSString *)c;

- (jint)getResponseStatus;

- (void)setMethodWithNSString:(NSString *)method;

- (void)remoteCallMakeOnThread;

- (void)addUrlParameterWithNSString:(NSString *)name
                             withId:(id)value;

- (void)setJsonPayloadWithNSString:(NSString *)json;

- (void)addParameterWithNSString:(NSString *)name
                          withId:(id)value;

- (void)addParameterWithNSString:(NSString *)name
                          withId:(id)value
                 withJavaUtilMap:(id<JavaUtilMap>)map;

- (void)setParamMapWithJavaUtilMap:(id<JavaUtilMap>)paramMap;

@end

J2OBJC_EMPTY_STATIC_INIT(MobilCall)

J2OBJC_TYPE_LITERAL_HEADER(MobilCall)

#define ComValsA2iosMobilighterIntfMobilCall MobilCall

#endif // _ComValsA2iosMobilighterIntfMobilCall_H_
