//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ..//android/com/vals/a2ios/mobilighter/intf/MobilColor.java
//

#ifndef _ComValsA2iosMobilighterIntfMobilColor_H_
#define _ComValsA2iosMobilighterIntfMobilColor_H_

#include "J2ObjC_header.h"

@protocol MobilColor < NSObject, JavaObject >

- (void)setRgbaWithFloat:(jfloat)r
               withFloat:(jfloat)g
               withFloat:(jfloat)b
               withFloat:(jfloat)a;

- (id)getColor;

@end

J2OBJC_EMPTY_STATIC_INIT(MobilColor)

J2OBJC_TYPE_LITERAL_HEADER(MobilColor)

#define ComValsA2iosMobilighterIntfMobilColor MobilColor

#endif // _ComValsA2iosMobilighterIntfMobilColor_H_
